# Font configuration
[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[general]
# Theme Nord
import = ["~/.config/alacritty/nord.toml"]

